travis:
  secure:
    BINSTAR_TOKEN: Bbjg9/E6w9XLPeE5FqvKKf42JxdnV1e8Jff/71FxfMkidaBB7nrjIoA7WtuwZy55Dbji9Xn/hVMi8IcI4qQbZyt9DyKakOszOczmHVHXKQELnubvR262qbHQcqhhxGyBMkq22cQW3En6SGeoGG5TZfFye44tya8dHc8gchrZoW9YkayMMt82ZtvjOf0SOH/rJxNiFYifq8TpCEj23r9pNL9Twu+0ehnWq0YlOwHWdosW7QfNYbhsNyBszwc9QXgxXjxRCSvxCNWfg2yHNl9WWRKDuIqEkaGHeRIrqAWJfsi7s1dzu5bjQNAAjdiOvjWNet4TQS2LjG3UeDlqVRrHPvDnWchoKHbxMPmGPPpeTZOB+6RTX6PPwrzB1O6zMnEHFPYrjpsYoFdOtlxXVXNxIYlilf5qBXJakgJWfVZrAuPkOmfYrtyzuKkkpZspyYzToBK9w0UODNF4iHYALWv49sForyEsidmXKncNDvx8KxhX421lP6gxPkt2lYqe3T6yIqlzQjLfDwePG2yfEIIzeHefapbDaUffz7zsbRMBFLihDN4emR18PC89strUNQR8qJrxjsx4W1xJuco1GaNTzNIJ22+hFEzRJHhjOn9+P8rN1sbVrKKxQBrgg0ScMDHy9nwaDf8k5L7dYFc+ciB3h5dzMgshd84CYwIgISpBT4s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
